[package]
name = "chess_engine_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.18.0"
url = "2.3.1"
"image" = "0.24.5"
"nanoid" = "0.4.0"
"rand" = "0.8.5"